[build-system]
requires = [
    "setuptools",
    "setuptools-scm<8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "syseng_throughputs"
description = "Rubin Observatory System Engineering Repository of Throughput Components"
readme = "README.md"
license = { text = "GPL" }
classifiers = [ 
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Astronomy",
 ]
urls = {repository = "https://github.com/lsst-pst/syseng_throughputs" }
dynamic = [ "version" ]
dependencies = [
    "numpy",
    "rubin_sim",
]


[project.scripts]
calc_m5 = "syseng_throughputs.bin:calc_m5"

[tool.setuptools.dynamic]
version = { attr = "setuptools_scm.get_version" }

[tool.setuptools.packages.find]
where = [ "" ]

[tool.setuptools_scm]
#version_file = "syseng_throughputs/version.py"
write_to = "syseng_throughputs/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""